trigger:
- master

pool: JoyceP53

variables:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk-17"
  MAVEN_HOME: "C:\\Users\\Joyce\\Install\\maven\\apache-maven-3.9.9"
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  EDGE_WEBDRIVER_PATH: "C:\\drivers"
  EDGE_BINARY_PATH: "C:\\Program Files (x86)\\Microsoft\\Edge\\Application"
  EDGE_DRIVER_LOGFILE: $(Agent.WorkFolder)\\logs\\edgedriver.log
  PATH: 'C:\\Windows\\System32;$(PATH);"$(JAVA_HOME)\\bin";"$(MAVEN_HOME)\\bin"'

steps:
- script: |
    echo "Java version:"
    java -version
    echo "Maven version:"
    mvn -version
    echo "Edge version:"
    msedgedriver --version
    echo "where Maven:"
    where mvn
  displayName: 'Check Environment'
  condition: succeededOrFailed()

# ----------------------
# Stage 1: Cache Maven Dependencies
# ----------------------
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
      maven
    path: $(MAVEN_CACHE_FOLDER)
  displayName: 'Cache Maven dependencies'

- script: |
    dir "$(EDGE_WEBDRIVER_PATH)\\msedgedriver.exe"
  displayName: 'Check Edge Driver Existence'

# ----------------------
# Stage 2: Maven Build (with cache)
# ----------------------
- script: |
    mvn clean install -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)
  displayName: 'Build package'
  condition: succeededOrFailed()

# ----------------------
# Stage 3: UI Test Execution (Headless Mode)
# ----------------------
- script: |
    mvn test -Dtest=SearchTest ^
      -Dwebdriver.edge.driver="$(EDGE_WEBDRIVER_PATH)\\msedgedriver.exe" ^
      -Dedge.binary.path="$(EDGE_BINARY_PATH)\\msedge.exe" ^
      -Dwebdriver.edge.logfile="$(EDGE_DRIVER_LOGFILE)" ^
      -Dwebdriver.edge.verboseLogging=true ^
      -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)
  displayName: 'Execute UI tests with Full Logging'
  env:
    EDGE_WEBDRIVER_PATH: $(EDGE_WEBDRIVER_PATH)
  condition: succeededOrFailed()

# ----------------------
# Stage 4: Test Results Publishing
# ----------------------
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mergeTestResults: true
  displayName: 'Publish Test Results'
  condition: succeededOrFailed()

# ----------------------
# Stage 5: Artifact Archiving
# ----------------------
- task: CopyFiles@2
  inputs:
    SourceFolder: 'target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Collect JAR Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'JarFiles'
  displayName: 'Publish JAR Artifacts'