# azure-pipelines.yml
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  JAVA_VERSION: '17'
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository  # Cache directory should point to repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'    # Force Maven to use cache directory with path safety

steps:
# ----------------------
# Stage 0: Cache Maven Dependencies
# ----------------------
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'   # Unique key based on OS and pom.xml
    restoreKeys: |                               # Fallback matching strategy
      maven | "$(Agent.OS)"
      maven
    path: $(MAVEN_CACHE_FOLDER)
  displayName: '缓存 Maven 依赖'

# ----------------------
# Stage 1: Java Environment Setup
# ----------------------
- task: JavaToolInstaller@0
  inputs:
    versionSpec: $(JAVA_VERSION)
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: 'Install Java 17'

# ----------------------
# Stage 2: Maven Build (with cache)
# ----------------------
- script: |
    mvn clean install -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)  
  displayName: 'Build package'

# ----------------------
# Stage 3: UI Test Execution
# ----------------------
- script: |
    mvn test -Dtest=SearchTest -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)
  displayName: 'Execute UI tests'
  env:
    EDGE_WEBDRIVER_PATH: $(System.DefaultWorkingDirectory)/drivers

# ----------------------
# Stage 4: Test Results Publishing
# ----------------------
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mergeTestResults: true
  displayName: 'Test Results Publishing'
  condition: succeededOrFailed()

# ----------------------
# Stage 5: Artifact Archiving
# ----------------------
- task: CopyFiles@2
  inputs:
    SourceFolder: 'target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Collect JAR artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'JarFiles'
  displayName: 'Publish JAR artifacts'