trigger:
- master

pool: JoyceP53

variables:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk-17"
  MAVEN_HOME: "C:\\Users\\Joyce\\Install\\maven\\apache-maven-3.9.9"
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  EDGE_WEBDRIVER_PATH: "C:\\drivers"
  PATH: 'C:\Windows\System32;$env:PATH;"$(JAVA_HOME)\bin";"$(MAVEN_HOME)\bin"'

steps:
- script: |
    echo "Java 版本:"
    java -version
    echo "Maven 版本:"
    mvn -version
    echo "Edge 版本:"
    msedgedriver --version
    echo "where Maven:"
    where mvn
  displayName: '环境检查'
  condition: succeededOrFailed()

# ----------------------
# Stage 1: Cache Maven Dependencies
# ----------------------
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
      maven
    path: $(MAVEN_CACHE_FOLDER)
  displayName: 'Cache Maven dependencies'

- script: |
    dir "%EDGE_WEBDRIVER_PATH%\msedgedriver.exe"
  displayName: '检查Edge驱动是否存在'
  
- script: |
    taskkill /f /im msedge.exe /t || echo "未找到 Edge 进程"
    taskkill /f /im msedgedriver.exe /t || echo "未找到 Edge 驱动进程"
  displayName: '清理残留进程'  
# ----------------------
# Stage 2: Maven Build (with cache)
# ----------------------
- script: |
    mvn clean install -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)
  displayName: 'Build package'

# ----------------------
# Stage 3: UI Test Execution (Headless Mode)
# ----------------------
- script: |
    mvn test -Dtest=SearchTest -Dbrowser.headless=true -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)
  displayName: 'Execute UI tests (Headless Edge)'
  env:
    EDGE_WEBDRIVER_PATH: $(EDGE_WEBDRIVER_PATH)  


# ----------------------
# Stage 4: Test Results Publishing
# ----------------------
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mergeTestResults: true
  displayName: 'Test Results Publishing'
  condition: succeededOrFailed()

# ----------------------
# Stage 5: Artifact Archiving
# ----------------------
- task: CopyFiles@2
  inputs:
    SourceFolder: 'target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Collect JAR artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'JarFiles'
  displayName: 'Publish JAR artifacts'