# azure-pipelines.yml
trigger:
- master  # 监听 master 分支触发构建

pool:
  vmImage: 'windows-latest'  # 必须使用 Windows 代理（预装 Edge）

variables:
  JAVA_VERSION: '17'

steps:
# ----------------------
# 阶段 1: Java 环境设置
# ----------------------
- task: JavaToolInstaller@0
  inputs:
    versionSpec: $(JAVA_VERSION)
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: '安装 Java 17'

# ----------------------
# 阶段 2: Maven 构建
# ----------------------
- script: |
    mvn clean install
  displayName: '编译和打包'

# ----------------------
# 阶段 3: UI 测试执行
# ----------------------
- script: |
    mvn test -Dtest=SearchTest
  displayName: '执行 UI 测试'
  env:
    EDGE_WEBDRIVER_PATH: $(System.DefaultWorkingDirectory)/drivers

# ----------------------
# 阶段 4: 测试结果发布
# ----------------------
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mergeTestResults: true
  displayName: '发布测试结果'
  condition: succeededOrFailed()

# ----------------------
# 阶段 5: 产物归档
# ----------------------
- task: CopyFiles@2
  inputs:
    SourceFolder: 'target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: '收集构建产物'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'JarFiles'
  displayName: '发布构建产物'