# azure-pipelines.yml
trigger:
- master  # 监听 main 分支的代码提交

pool:
  vmImage: 'windows-latest'  # 使用微软托管代理

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository

steps:
- task: Cache@2  # Maven 依赖缓存加速
  inputs:
    key: 'maven | "$(Agent.OS)" | pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
    path: $(MAVEN_CACHE_FOLDER)

steps:
- task: JavaToolInstaller@0  # 关键步骤
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: java -version  # 验证版本
  displayName: '检查 Java 版本'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-DskipTests=true'  # 可选：跳过测试


- task: CopyFiles@2  # 打包产物归档
  inputs:
    SourceFolder: 'target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- script: |
    echo "验证 Edge 浏览器版本"
    reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\EdgeUpdate\Clients\{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}" /v pv
  displayName: '检查 Edge 版本'

- script: |
    echo "运行 UI 测试"
    mvn test -Dtest=SearchTest
  displayName: '执行 UI 测试'
  env:
    EDGE_WEBDRIVER_PATH: $(System.DefaultWorkingDirectory)/drivers

- script: |
    mvn allure:report
  displayName: '生成 Allure 报告'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'Allure'
    testResultsFiles: 'allure-results/*.xml'
- task: PublishBuildArtifacts@1  # 发布构建产物
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "##vso[task.complete result=Succeeded;]DONE"
  displayName: '发送通知'
  condition: always()
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

